project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"

website:
  open-graph: true
  title: "Daniel Kaiser"
  site-url: https://kaiser-dan.github.io
  repo-url: https://github.com/kaiser-dan/kaiser-dan.github.io
  favicon: assets/images/uva.ico

  navbar:
    style: "floating"
    background: dark
    foreground: light
    left:
      - href: index.qmd
        text: Home
      - text: Research
        menu:
          - href: pages/research/projects.qmd
            text: Projects
          - href: pages/research/publications.qmd
            text: Publications
      - text: "Teaching & mentoring"
        menu:
          - href: pages/teaching/teaching.qmd
            text: Teaching
          - href: pages/teaching/mentoring.qmd
            text: Mentoring
      - text: Resources
        menu:
          - href: pages/resources/resources.qmd
            text: Resources
          - href: pages/resources/software.qmd
            text: Software
      - text: About
        menu:
          - text: Myself
            href: pages/aboutme.qmd
          - text: Co-authors
            href: pages/coauthors.qmd
          - text: Department
            href: https://www.eebvirginia.org/
      - href: assets/docs/CV_Kaiser_Daniel.pdf
        text: CV
    search: true
    pinned: true

format:
  html:
    theme: spacelab
    mainfont: franklin-gothic, sans-serif
    toc: true
    smooth-scroll: true
    html-math-method: katex
    include-in-header:
      - includes.html
    footnotes-hover: false
    code-fold: true