---
title: "Resources"
toc: true
---

::: {.callout-warning}
**Page under construction. For now, see [Dr. Phil Chodrow's website](https://www.philchodrow.prof/resources.html) for a similarly inspired Resources page (and the inspiration for my own intended page).**
:::

Conducting scientific research is a difficult endeavour in any field or time. 
Computational sciences in the modern era are no different; between mathematical skills and tools and software requirements and changing capabilities, it is no easy task to complete scientific computations at all, much less to do so efficiently.

I have compiled several resources to help me engage in computational science, from books and articles to packages and heuristics, I have found wisdom from others to aide nearly all aspects of my work. Some of these resources I have created myself but most I have compiled from others selflish open publication.

Below are some of the resources I have used/created and would recommend. Most should be future-proof indefinitely or for at least many years, but I cannot guarantee any that are not my own creation are up-to-date with modern computational systems. I would be happy to help troubleshoot any problems you may encounter.

I have categorized the resources by topic they address, given as headers on this page. Note that some resources appear under many headers.



## Note-taking & presenting research

## Reproducibility

## Mathematics

## Scientific programming
